# Generated by Django 5.1.3 on 2024-11-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_initial'),
        ('notifications', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issue',
            new_name='JiraniIssue',
        ),
    ]
