# Generated by Django 5.1.3 on 2024-11-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_rename_posted_by_announcement_chief_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='chief',
        ),
    ]
